[package]
name = "rendezvous_client"
version = "0.1.0"
edition = "2024"
description = "Simple WebSocket connector for Osvauld"
authors = ["Osvauld Team"]

[dependencies]
futures-lite = "2.6.0"
futures-util = "0.3.31"
log = "0.4.26"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1.44.0", features = ["rt", "sync", "macros", "time"] }
tokio-tungstenite = { version = "0.26.2", features = ["native-tls"] }
url = "2.5.4"


tracing = "0.1.41"
tracing-appender = "0.2.3"
osvauld_services = { path = "../osvauld-services" }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

osvauld_core = { path = "../core" }
p2p_service = { path = "../p2p-service" }
tracing-log = "0.2.0"
chrono = "0.4.40"
[lib]
name = "rendezvous_client"
path = "src/lib.rs"
crate-type = ["lib"]
