packages:
  # Frontend apps
  - 'livnote/frontend/desktop'
  - 'libremot/frontend/desktop'
  
  # Shared packages
  - 'icons'
  - 'packages/*'
  
  # Core packages
  - 'core'
  - 'crypto_utils'
  - 'network'
  - 'services'
  - 'persistance'
  - 'search_indexer'
