[package]
name = "network"
version = "0.1.0"
edition = "2021"
description = "P2P communication library for Osvauld"
authors = ["Osvauld Team"]
license = "MIT"
repository = "https://github.com/osvauld/osvauld"

[dependencies]
# Core dependencies
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8.5"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["full"] }
iroh-quinn = "0.14.0"
iroh-blobs = "0.35.0"
iroh = "0.90.0"
anyhow = "1.0.91"
futures-lite = "2.3.0"
iroh-base = "0.90.0"

# Osvauld core dependencies
osvauld_core = { version = "0.1.0", path = "../core" }
services = { version = "0.1.0", path = "../services" }
crypto_utils = { path = "../crypto_utils" }
persistance = { path = "../persistance" }
tracing = { version = "0.1.41", features = ["attributes"] }
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tracing-log = "0.2.0"
n0-watcher = "0.2.0"
base64 = "0.22.1"

[features]
default = []
