[package]
name = "services"
version = "0.1.0"
edition = "2024"
description = "Service layer for Osvauld application"

[dependencies]
osvauld_core = { path = "../core" }
crypto_utils = { path = "../crypto_utils" }
persistance = { path = "../persistance" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"
tokio = { version = "1.44.2", features = ["sync"] }
thiserror = "2.0.0"
rand = "0.8.5"
base64 = "0.22.1"
uuid = { version = "1.11.0", features = ["v4"] }
chrono = "0.4"
loro = "1.1.2"
ed25519-dalek = "2.1.1"
ucan = "0.4.0"

tracing = "0.1.41"
tracing-appender = "0.2.3"


tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
tracing-log = "0.2.0"
