(executable
 (name cel_wasm)
 (modules logging cel_wasm reactive_state)
 (libraries cel js_of_ocaml js_of_ocaml-ppx logs logs.browser react)
 (preprocess
  (pps js_of_ocaml-ppx))
 (modes wasm))

; WASI target for native Rust integration (no JS dependencies)
(executable
 (name cel_wasi)
 (modules cel_wasi)
 (libraries cel str yojson)
 (modes (best exe)))
